<?php

namespace AssignmentBundle\Repository;

/**
 * CategoryProgressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryProgressRepository extends \Doctrine\ORM\EntityRepository
{
}
