dashboard:
    resource: "@DashboardBundle/Controller/"
    type:     annotation
    prefix:   /

home:
    resource: "@HomeBundle/Controller/"
    type:     annotation
    prefix:   /

assignment:
    resource: "@AssignmentBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

course:
    resource: "@CourseBundle/Controller/"
    type:     annotation
    prefix:   /



